export const CartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  INCREASE_CART_QUANTITY: "INCREASE_CART_QUANTITY",
  DECREASE_CART_QUANTITY: "DECREASE_CART_QUANTITY"
};
